config/routes.rb
Rails.application.routes.draw do
  resources :votes, only: [:create,:destroy]

  devise_for :users
  resources :ideas
  resources :terms, only: [:index,:show]
  root  "static_pages#home"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
      user ||= User.new # guest user (not logged in)
      can :read, Idea
      can :manage, Idea, user_id: user.id

    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  validates_presence_of :question
  validates_presence_of :explanation

  belongs_to :term
  belongs_to :user
  has_many   :votes
end

app/models/term.rb
class Term < ActiveRecord::Base
  has_many :ideas
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :ideas
  has_many :votes
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  validates :idea, uniqueness: {scope: :user}
  belongs_to :user
  belongs_to :idea

  def self.has_voted?(user,idea)
    if self.where(user: user, idea: idea).count > 0
      return true
    else
      return false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:show, :index]
  load_and_authorize_resource

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
    @votes_count = @idea.votes.count
  end

  # GET /ideas/new
  def new
    @term_id = idea_from_term_params[:term] || nil
    @idea = Idea.new()
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)
    if idea_params[:term_id]
      @term = Term.find(idea_params[:term_id])
    end
    respond_to do |format|
      if @idea.save
        format.html { redirect_to @term, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:question, :explanation, :term_id, :user_id)
    end

    def idea_from_term_params
      params.permit(:term)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
  before_action :set_term, only: [:show]

def index
  @terms = Term.all
end

def show
end

private
  def set_term
   @term = Term.find(params[:id])
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

before_action :set_vote, only: :destroy

def create
  vote = Vote.create(votes_params)
  redirect_to :back
end

def destroy
  @vote.destroy
  redirect_to :back
end

private
  def votes_params
    params.permit(:idea_id, :user_id)
  end

  def set_vote
    @vote = Vote.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :term_id, value: @term_id %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <div class="field">
    <%= f.label :question %><br>
    <%= f.text_field :question %>
  </div>
  <div class="field">
    <%= f.label :explanation %><br>
    <%= f.text_area :explanation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ideas/_idea.html.erb
<div class="row well">
<div class="col-sm-2">
  <%= render 'votes/votes', votes: idea.votes %>
  <% unless Vote.has_voted?(current_user,idea) %>
    <%= render 'votes/form', idea: idea %>
  <%else%>
    <%= render 'votes/delete', vote: Vote.where(user: current_user, idea: idea).first %>
  <%end%>
</div>
<div class="col-sm-10">
<div class="row">
  <div class="col-sm-10">
      <h3><%= link_to idea.question, idea%></h3>
  </div>
  <div class="col-sm-2">
    <%= link_to 'Edit', edit_idea_path(idea), class: 'btn btn-default' if can? :update, idea %>
  </div>
</div>

<div class="row">
  <div class="col-sm-12">
    <%= idea.explanation %>
  </div>
</div>
</div>


</div>

app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ideas</h1>

<div class="row">
  <div class="col-md-3">
    <h2>Question</h2>
  </div>
  <div class="col-md-3">
    <h2>Explanation</h2>
  </div>
  <div class="col-md-3">
    <h2>User</h2>
  </div>
</div>


<% @ideas.each do |idea| %>
  <%= render idea%>
<% end %>
<br>

app/views/ideas/new.html.erb
<h1>New Idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<div class="row well">
  <div class="col-sm-2">
    <%= render 'votes/votes', votes: @idea.votes %>
    <%= render 'votes/form', idea: @idea %>
  </div>
  <div class="col-sm-10">
    <div class="row">
      <div class="col-sm-10">
        <h3><%= link_to @idea.question, @idea%></h3>
      </div>
      <div class="col-sm-2">
        <%= link_to 'Edit', edit_idea_path(@idea), class: 'btn btn-default' if can? :update, @idea %>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-12">
        <%= @idea.explanation %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Leitfrage</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Die richtige Frage</a>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="/">Home</a></li>
          <li><a href="/terms">Begriffe</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li> <a href="#">Welcome, <%= current_user.email %> </a></li>
          <li><%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "btn" %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path, class: "btn" %></li>
        <% end %>
      </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>



  <div class="container">
    <%= yield %>
  </div>


</body>
</html>

app/views/static_pages/home.html.erb
<div>
  This is the homepage
</div>

app/views/terms/index.html.erb
<ul>
  <% @terms.each do |term| %>
  <li> <%= link_to term.name, term_url(term) %></li>
  <%end%>
</ul>

app/views/terms/show.html.erb
<h2><%=@term.name%></h2>

  <% @term.ideas.each do |idea| %>
  <%= render idea %>
  <%end%>
  <%= link_to "Erstell eine neue Idee", new_idea_path(term: @term)%>

app/views/votes/_delete.html.erb
<p>Allready Voted</p>
<%= link_to 'Remove Vote', vote_path(vote), method: 'delete', class: 'btn btn-default' %>

app/views/votes/_form.html.erb
<%= form_tag("/votes", method: "post") do %>
  <%= hidden_field_tag :idea_id,  idea.id %>
  <%= hidden_field_tag :user_id,  current_user.id %>
  <%= submit_tag("Vote Up", class: 'btn btn-default') %>
<% end %>

app/views/votes/_votes.html.erb
Votes: <%= votes.count %>